// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqVBuXR5Aec7dS_7UbGOM0eDWSrunkN0M',
    appId: '1:325844520117:web:f4bd09f909e274109702fc',
    messagingSenderId: '325844520117',
    projectId: 'chatapp-6d9d7',
    authDomain: 'chatapp-6d9d7.firebaseapp.com',
    storageBucket: 'chatapp-6d9d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUYHqeZy9XoAI8fxRqyRJ0lsW-GrMelE',
    appId: '1:325844520117:android:a2ddd64a03378e6c9702fc',
    messagingSenderId: '325844520117',
    projectId: 'chatapp-6d9d7',
    storageBucket: 'chatapp-6d9d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMUTdeB56fgnbA1d8oFjcS_3LlVHbNVrM',
    appId: '1:325844520117:ios:00279b779d577b619702fc',
    messagingSenderId: '325844520117',
    projectId: 'chatapp-6d9d7',
    storageBucket: 'chatapp-6d9d7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMUTdeB56fgnbA1d8oFjcS_3LlVHbNVrM',
    appId: '1:325844520117:ios:00279b779d577b619702fc',
    messagingSenderId: '325844520117',
    projectId: 'chatapp-6d9d7',
    storageBucket: 'chatapp-6d9d7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqVBuXR5Aec7dS_7UbGOM0eDWSrunkN0M',
    appId: '1:325844520117:web:8283efbecf3c04309702fc',
    messagingSenderId: '325844520117',
    projectId: 'chatapp-6d9d7',
    authDomain: 'chatapp-6d9d7.firebaseapp.com',
    storageBucket: 'chatapp-6d9d7.firebasestorage.app',
  );
}
